// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./protofile.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: protofile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessengerServer_AskPrice_FullMethodName = "/pricepb.MessengerServer/askPrice"
)

// MessengerServerClient is the client API for MessengerServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessengerServerClient interface {
	AskPrice(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
}

type messengerServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessengerServerClient(cc grpc.ClientConnInterface) MessengerServerClient {
	return &messengerServerClient{cc}
}

func (c *messengerServerClient) AskPrice(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, MessengerServer_AskPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessengerServerServer is the server API for MessengerServer service.
// All implementations must embed UnimplementedMessengerServerServer
// for forward compatibility.
type MessengerServerServer interface {
	AskPrice(context.Context, *AskRequest) (*AskResponse, error)
	mustEmbedUnimplementedMessengerServerServer()
}

// UnimplementedMessengerServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessengerServerServer struct{}

func (UnimplementedMessengerServerServer) AskPrice(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskPrice not implemented")
}
func (UnimplementedMessengerServerServer) mustEmbedUnimplementedMessengerServerServer() {}
func (UnimplementedMessengerServerServer) testEmbeddedByValue()                         {}

// UnsafeMessengerServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessengerServerServer will
// result in compilation errors.
type UnsafeMessengerServerServer interface {
	mustEmbedUnimplementedMessengerServerServer()
}

func RegisterMessengerServerServer(s grpc.ServiceRegistrar, srv MessengerServerServer) {
	// If the following call pancis, it indicates UnimplementedMessengerServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessengerServer_ServiceDesc, srv)
}

func _MessengerServer_AskPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServerServer).AskPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessengerServer_AskPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServerServer).AskPrice(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessengerServer_ServiceDesc is the grpc.ServiceDesc for MessengerServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessengerServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricepb.MessengerServer",
	HandlerType: (*MessengerServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "askPrice",
			Handler:    _MessengerServer_AskPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofile.proto",
}
